---
title: "R Notebook"
output: html_notebook
---
```{r "setup", include=FALSE}
#Set the WD here
knitr::opts_knit$set(root.dir = normalizePath('C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/PD_Results_Jan2021/'))
library(tidyverse)
library(plyr)

```

```{r}
df <- read.table("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/PD_Results_Jan2021/OddReplicates_PSMs.txt", header = T)

df$Modifications <- gsub("C[0-9]{1,2}\\(Carbamidomethyl)\\;{0,1}\\s{0,1}","",df$Modifications,fixed = FALSE)

# Relabel Acetyl (nterm)
df$Modifications <- gsub("N-Term\\(Prot\\)\\(Acetyl\\)\\;{0,1}\\s{0,1}", "ntermAcetyl_", df$Modifications, fixed = FALSE)

# Relabel Acetyl 
df$Modifications <- gsub("\\(Acetyl\\)\\;{0,1}\\s{0,1}", "acetyl_", df$Modifications, fixed = FALSE)

# Relabel Oxidation                            
df$Modifications <- gsub("M[0-9]{1,2}\\(Oxidation\\)\\;{0,1}\\s{0,1}", "",df$Modifications, fixed = FALSE)

# Relabel Methylation                            
df$Modifications <- gsub("\\(Methyl\\)\\;{0,1}\\s{0,1}", "me1_",df$Modifications, fixed = FALSE)

# Relabel Dimethylation                            
df$Modifications <- gsub("\\(Dimethyl\\)\\;{0,1}\\s{0,1}", "me2_",df$Modifications, fixed = FALSE)

# Remove final _                           
df$Modifications <- gsub("\\_$", "",df$Modifications, fixed = FALSE)

df$group <- 'Other'
df[grep('me',df$Modifications), 'group'] <- 'methyl'



df <- df[grep('group|Charge', colnames(df))]

df$group <- factor(df$group, levels = c('Other','methyl'))

ggplot(df, aes(x = Charge, fill = group)) +  
  geom_bar(aes(y = (..count..)/sum(..count..)), position=position_dodge())+
  scale_fill_manual(values = c('#bababa','#4d4d4d'))+
    theme(legend.position = "right",
        axis.text.y   = element_text(size=12, colour = "black"),
        axis.text.x   = element_text(size=12, colour = "black"),
        axis.title.y  = element_text(size=12, colour = "black"),
        axis.title.x  = element_text(size=12, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_x_continuous(breaks = round(seq(min(df$Charge), max(df$Charge), by = 1),1))+
  ylim(0,0.4)
```

```{r}
df <- read.table("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/PD_Results_Jan2021/GluC_MethylIP_PSMs.txt", header = T)

df$Modifications <- gsub("C[0-9]{1,2}\\(Carbamidomethyl)\\;{0,1}\\s{0,1}","",df$Modifications,fixed = FALSE)

# Relabel Acetyl (nterm)
df$Modifications <- gsub("N-Term\\(Prot\\)\\(Acetyl\\)\\;{0,1}\\s{0,1}", "ntermAcetyl_", df$Modifications, fixed = FALSE)

# Relabel Acetyl 
df$Modifications <- gsub("\\(Acetyl\\)\\;{0,1}\\s{0,1}", "acetyl_", df$Modifications, fixed = FALSE)

# Relabel Oxidation                            
df$Modifications <- gsub("M[0-9]{1,2}\\(Oxidation\\)\\;{0,1}\\s{0,1}", "",df$Modifications, fixed = FALSE)

# Relabel Methylation                            
df$Modifications <- gsub("\\(Methyl\\)\\;{0,1}\\s{0,1}", "me1_",df$Modifications, fixed = FALSE)

# Relabel Dimethylation                            
df$Modifications <- gsub("\\(Dimethyl\\)\\;{0,1}\\s{0,1}", "me2_",df$Modifications, fixed = FALSE)

# Remove final _                           
df$Modifications <- gsub("\\_$", "",df$Modifications, fixed = FALSE)

df$group <- 'Other'
df[grep('me',df$Modifications), 'group'] <- 'methyl'



df <- df[grep('group|Charge', colnames(df))]

df$group <- factor(df$group, levels = c('Other','methyl'))

ggplot(df, aes(x = Charge, fill = group)) +  
  geom_bar(aes(y = (..count..)/sum(..count..)), position=position_dodge())+
  scale_fill_manual(values = c('#bababa','#4d4d4d'))+
    theme(legend.position = "right",
        axis.text.y   = element_text(size=12, colour = "black"),
        axis.text.x   = element_text(size=12, colour = "black"),
        axis.title.y  = element_text(size=12, colour = "black"),
        axis.title.x  = element_text(size=12, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_x_continuous(breaks = round(seq(min(df$Charge), max(df$Charge), by = 1),1))+
  ylim(0,0.4)
```

```{r}
df <- read.table("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/PD_Results_Jan2021/TrypsinMethyl_IP_PSMs.txt", header = T)

df$Modifications <- gsub("C[0-9]{1,2}\\(Carbamidomethyl)\\;{0,1}\\s{0,1}","",df$Modifications,fixed = FALSE)

# Relabel Acetyl (nterm)
df$Modifications <- gsub("N-Term\\(Prot\\)\\(Acetyl\\)\\;{0,1}\\s{0,1}", "ntermAcetyl_", df$Modifications, fixed = FALSE)

# Relabel Acetyl 
df$Modifications <- gsub("\\(Acetyl\\)\\;{0,1}\\s{0,1}", "acetyl_", df$Modifications, fixed = FALSE)

# Relabel Oxidation                            
df$Modifications <- gsub("M[0-9]{1,2}\\(Oxidation\\)\\;{0,1}\\s{0,1}", "",df$Modifications, fixed = FALSE)

# Relabel Methylation                            
df$Modifications <- gsub("\\(Methyl\\)\\;{0,1}\\s{0,1}", "me1_",df$Modifications, fixed = FALSE)

# Relabel Dimethylation                            
df$Modifications <- gsub("\\(Dimethyl\\)\\;{0,1}\\s{0,1}", "me2_",df$Modifications, fixed = FALSE)

# Remove final _                           
df$Modifications <- gsub("\\_$", "",df$Modifications, fixed = FALSE)

df$group <- 'Other'
df[grep('me',df$Modifications), 'group'] <- 'methyl'



df <- df[grep('group|Charge', colnames(df))]

df$group <- factor(df$group, levels = c('Other','methyl'))

ggplot(df, aes(x = Charge, fill = group)) +  
  geom_bar(aes(y = (..count..)/sum(..count..)), position=position_dodge())+
  scale_fill_manual(values = c('#bababa','#4d4d4d'))+
    theme(legend.position = "right",
        axis.text.y   = element_text(size=12, colour = "black"),
        axis.text.x   = element_text(size=12, colour = "black"),
        axis.title.y  = element_text(size=12, colour = "black"),
        axis.title.x  = element_text(size=12, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_x_continuous(breaks = round(seq(min(df$Charge), max(df$Charge), by = 1),1))
  #ylim(0,0.4)
```
```{r}
df <- read.table("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/PD_Results_Jan2021/Input_Tryp_PSMs.txt", header = T)

df$Modifications <- gsub("C[0-9]{1,2}\\(Carbamidomethyl)\\;{0,1}\\s{0,1}","",df$Modifications,fixed = FALSE)

# Relabel Acetyl (nterm)
df$Modifications <- gsub("N-Term\\(Prot\\)\\(Acetyl\\)\\;{0,1}\\s{0,1}", "ntermAcetyl_", df$Modifications, fixed = FALSE)

# Relabel Acetyl 
df$Modifications <- gsub("\\(Acetyl\\)\\;{0,1}\\s{0,1}", "acetyl_", df$Modifications, fixed = FALSE)

# Relabel Oxidation                            
df$Modifications <- gsub("M[0-9]{1,2}\\(Oxidation\\)\\;{0,1}\\s{0,1}", "",df$Modifications, fixed = FALSE)

# Relabel Methylation                            
df$Modifications <- gsub("\\(Methyl\\)\\;{0,1}\\s{0,1}", "me1_",df$Modifications, fixed = FALSE)

# Relabel Dimethylation                            
df$Modifications <- gsub("\\(Dimethyl\\)\\;{0,1}\\s{0,1}", "me2_",df$Modifications, fixed = FALSE)

# Remove final _                           
df$Modifications <- gsub("\\_$", "",df$Modifications, fixed = FALSE)

df$group <- 'Other'
df[grep('me',df$Modifications), 'group'] <- 'methyl'



df <- df[grep('group|Charge', colnames(df))]

df$group <- factor(df$group, levels = c('Other','methyl'))

ggplot(df, aes(x = Charge, fill = group)) +  
  geom_bar(aes(y = (..count..)/sum(..count..)), position=position_dodge())+
  scale_fill_manual(values = c('#bababa','#4d4d4d'))+
    theme(legend.position = "right",
        axis.text.y   = element_text(size=12, colour = "black"),
        axis.text.x   = element_text(size=12, colour = "black"),
        axis.title.y  = element_text(size=12, colour = "black"),
        axis.title.x  = element_text(size=12, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_x_continuous(breaks = round(seq(min(df$Charge), max(df$Charge), by = 1),1))
  #ylim(0,0.4)
```