---
title: "FUS and TAF15 Rme changes"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

### Created: 4.6.21


### Notes:   
```{r "setup", include=FALSE}
#Set the WD here
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

knitr::opts_knit$set(root.dir = normalizePath('C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/'))
library(tidyverse)
library(rio)
library(ggplot2)
library(viridisLite)
library(purrr)
library(ggrepel)
library(plotly)

```

```{r}

GluC <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/GluC_02/Gluc_MMA_ADMA_SDMA_PerResidue.csv")




Trypsin <-  read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/Tryp_02/Trypsin_MMA_ADMA_SDMA_PerResidue.csv")

```



```{r}
df <- Trypsin[Trypsin$MS023_vs_GSK591_p.val < 0.05,]
df <- df[df$Accession == 'P35637',]
df[grep('me1',df$value), 'group'] <- 'me1'
df[grep('me2',df$value), 'group'] <- 'me2'

ggplot(df, aes(x=Gene.Symbol, y=MS023_vs_GSK591_diff, color = group)) +
  geom_jitter(aes(size=-log2(MS023_vs_GSK591_p.val)),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#fdbb84','#7f0000')) +
  #geom_text_repel(data = df, aes(label=value),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "right",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-1,1)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

df <- Trypsin[Trypsin$MS023_vs_GSK591_p.val < 0.05,]
df <- df[df$Accession == 'Q92804',]
df[grep('me1',df$value), 'group'] <- 'me1'
df[grep('me2',df$value), 'group'] <- 'me2'

ggplot(df, aes(x=Gene.Symbol, y=MS023_vs_GSK591_diff, color = group)) +
  geom_jitter(aes(size=-log2(MS023_vs_GSK591_p.val)),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#fdbb84','#7f0000')) +
  #geom_text_repel(data = df, aes(label=value),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "right",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-1,1)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```
```{r}
df <- Trypsin[Trypsin$GSK591_vs_DMSO_p.val < 0.05,]
df <- df[df$Accession == 'P35637',]
df[grep('me1',df$value), 'group'] <- 'me1'
df[grep('me2',df$value), 'group'] <- 'me2'


ggplot(df, aes(x=Gene.Symbol, y=GSK591_vs_DMSO_diff, color = group)) +
  geom_jitter(aes(size=-log2(GSK591_vs_DMSO_p.val)),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#fdbb84','#7f0000')) +
  #geom_text_repel(data = df, aes(label=value),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "right",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-1,1)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

df <- Trypsin[Trypsin$GSK591_vs_DMSO_p.val < 0.05,]
df <- df[df$Accession == 'Q92804',]
df[grep('me1',df$value), 'group'] <- 'me1'
df[grep('me2',df$value), 'group'] <- 'me2'

ggplot(df, aes(x=Gene.Symbol, y=GSK591_vs_DMSO_diff, color = group)) +
  geom_jitter(aes(size=-log2(GSK591_vs_DMSO_p.val)),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#fdbb84','#7f0000')) +
  #geom_text_repel(data = df, aes(label=value),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "right",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-1,1)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```


```{r}
df <- Trypsin[Trypsin$MS023_vs_DMSO_p.val < 0.05,]
df <- df[df$Accession == 'P35637',]
df[grep('me1',df$value), 'group'] <- 'me1'
df[grep('me2',df$value), 'group'] <- 'me2'


ggplot(df, aes(x=Gene.Symbol, y=MS023_vs_DMSO_diff, color = group)) +
  geom_jitter(aes(size=-log2(MS023_vs_DMSO_p.val)),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#fdbb84','#7f0000')) +
  #geom_text_repel(data = df, aes(label=value),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "right",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-1,1)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

df <- Trypsin[Trypsin$MS023_vs_DMSO_p.val < 0.05,]
df <- df[df$Accession == 'Q92804',]
df[grep('me1',df$value), 'group'] <- 'me1'
df[grep('me2',df$value), 'group'] <- 'me2'

ggplot(df, aes(x=Gene.Symbol, y=MS023_vs_DMSO_diff, color = group)) +
  geom_jitter(aes(size=-log2(MS023_vs_DMSO_p.val)),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#fdbb84','#7f0000')) +
  #geom_text_repel(data = df, aes(label=value),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "right",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-1,1)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```