---
title: "IP ontology"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r "setup", include=FALSE}
#Set the WD here
knitr::opts_chunk$set(fig.width=16, fig.height=12) 
library(clusterProfiler)
library(DOSE)
options(connectionObserver = NULL)
library(org.Hs.eg.db)
library(enrichplot)
library(biomaRt)
library(dplyr)
library(ggplot2)
```

```{r}

MMA_trypsin <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/MMA_Trypsin_Peptide.csv")
MMA_trypsin$data <- 'Trypsin'
ADMA_trypsin <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/ADMA_Trypsin_Peptide.csv")
ADMA_trypsin$data <- 'Trypsin'
SDMA_trypsin <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/SDMA_Trypsin_Peptide.csv")
SDMA_trypsin$data <- 'Trypsin'

MMA_gluc <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/GluC_MMA_Peptide.csv")
MMA_gluc$data <- 'GluC'
ADMA_gluc <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/GluC_ADMA_Peptide.csv")
ADMA_gluc$data <- 'GluC'
SDMA_gluc <- read.csv("C:/Users/maxim/OneDrive - Montefiore Medicine/Shechter/Processed_Data/GluC_SDMA_Peptide.csv")
SDMA_gluc$data <- 'GluC'

```

```{r}
df_MMA <- rbind(MMA_trypsin, MMA_gluc)
df_MMA <- df_MMA[grep('R', df_MMA$Modifications),]
df_ADMA <- rbind(ADMA_trypsin, ADMA_gluc)
df_ADMA <- df_ADMA[grep('R', df_ADMA$Modifications),]
df_SDMA <- rbind(SDMA_trypsin, SDMA_gluc)
df_SDMA <- df_SDMA[grep('R', df_SDMA$Modifications),]


df_MMA_GSK591 <- df_MMA[df_MMA$GSK591_MMA_vs_DMSO_MMA_p.val < 0.1,]
df_MMA_GSK591 <- df_MMA_GSK591[order(df_MMA_GSK591$GSK591_MMA_vs_DMSO_MMA_p.val, decreasing = FALSE),]

df_ADMA_GSK591 <- df_ADMA[df_ADMA$GSK591_ADMA_vs_DMSO_ADMA_p.val < 0.1,]
df_ADMA_GSK591 <- df_ADMA_GSK591[order(df_ADMA_GSK591$GSK591_ADMA_vs_DMSO_ADMA_p.val, decreasing = FALSE),]

df_SDMA_GSK591 <- df_SDMA[df_SDMA$GSK591_SDMA_vs_DMSO_SDMA_p.val < 0.1,]
df_SDMA_GSK591 <- df_SDMA_GSK591[order(df_SDMA_GSK591$GSK591_SDMA_vs_DMSO_SDMA_p.val, decreasing = FALSE),]

df_MMA_MS023 <- df_MMA[df_MMA$MS023_MMA_vs_DMSO_MMA_p.val < 0.1,]
df_MMA_MS023 <- df_MMA_MS023[order(df_MMA_MS023$MS023_MMA_vs_DMSO_MMA_p.val, decreasing = FALSE),]

df_ADMA_MS023 <- df_ADMA[df_ADMA$MS023_ADMA_vs_DMSO_ADMA_p.val < 0.1,]
df_ADMA_MS023 <- df_ADMA_MS023[order(df_ADMA_MS023$MS023_ADMA_vs_DMSO_ADMA_p.val, decreasing = FALSE),]

df_SDMA_MS023 <- df_SDMA[df_SDMA$MS023_SDMA_vs_DMSO_SDMA_p.val < 0.1,]
df_SDMA_MS023 <- df_SDMA_MS023[order(df_SDMA_MS023$MS023_SDMA_vs_DMSO_SDMA_p.val, decreasing = FALSE),]


dataframes_GSK591 <- list(MMA_GSK591 = df_MMA_GSK591, ADMA_GSK591 = df_ADMA_GSK591, SDMA_GSK591 = df_SDMA_GSK591)
dataframes_MS023 <- list(MMA_MS023 = df_MMA_MS023, ADMA_MS023 = df_ADMA_MS023, SDMA_MS023 = df_SDMA_MS023)
```

```{r}
#load in the dataframes
dataframes_GSK591 <- lapply(dataframes_GSK591, function(x) {colnames(x)[28] <- 'pval';x})
dataframes_MS023 <- lapply(dataframes_MS023, function(x) {colnames(x)[33] <- 'pval';x})
dataframes_GSK591 <- lapply(dataframes_GSK591, function(x) {colnames(x)[26] <- 'log2FoldChange';x})
dataframes_MS023 <- lapply(dataframes_MS023, function(x) {colnames(x)[31] <- 'log2FoldChange';x})

dataframes <- c(dataframes_GSK591, dataframes_MS023)
dataframes <- lapply(dataframes, function(x) x[!duplicated(x$Accession),])

mart <- useMart(biomart="ENSEMBL_MART_ENSEMBL", host="grch37.ensembl.org", path="/biomart/martservice", dataset="hsapiens_gene_ensembl")
dataframes_symbol <- lapply(dataframes, function(x) getBM(filters= "uniprotswissprot", attributes= c("uniprotswissprot","entrezgene_id"),values=x[12],mart= mart))
dataframes_symbol <- lapply(dataframes_symbol, setNames, c("Accession","entrez"))
dataframes <-mapply(merge, dataframes, dataframes_symbol, SIMPLIFY = FALSE)
dataframes <- lapply(dataframes, function(x) x[!duplicated(x$Accession),])

dataframes <- lapply(dataframes, function(x) x[order(x$pval),])
dataframes <- lapply(dataframes, function(x) x[!is.na(x$entrez),])

df <- dataframes %>% bind_rows(.id = 'df')

```


```{r}
require(clusterProfiler)
formula_GO_BP <- compareCluster(entrez~df, data = df, fun="enrichGO",  OrgDb = org.Hs.eg.db, ont = 'BP', pAdjustMethod = "BH", pvalueCutoff = 0.05, qvalueCutoff = 0.05)
formula_GO_simple_BP <-  simplify(formula_GO_BP, cutoff=0.7, by="p.adjust", select_fun=min)
formula_GO_MF <- compareCluster(entrez~df, data = df, fun="enrichGO",  OrgDb = org.Hs.eg.db, ont = 'MF', pAdjustMethod = "BH", pvalueCutoff = 0.05, qvalueCutoff = 0.05)
formula_GO_simple_MF <-  simplify(formula_GO_MF, cutoff=0.7, by="p.adjust", select_fun=min)
formula_GO_CC <- compareCluster(entrez~df, data = df, fun="enrichGO",  OrgDb = org.Hs.eg.db, ont = 'CC', pAdjustMethod = "BH", pvalueCutoff = 0.05, qvalueCutoff = 0.05)
formula_GO_simple_CC <-  simplify(formula_GO_CC, cutoff=0.7, by="p.adjust", select_fun=min)

dotplot(formula_GO_simple_BP, showCategory = 20)+ scale_color_gradient(low = '#E76F00', high='#55439B' ) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))

dotplot(formula_GO_simple_MF, showCategory = 20)+ scale_color_gradient(low = '#E76F00', high='#55439B' ) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))

dotplot(formula_GO_simple_CC, showCategory = 20)+ scale_color_gradient(low = '#E76F00', high='#55439B' ) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```
