---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---
```{r "setup", include=FALSE}
#Set the WD here
knitr::opts_chunk$set(fig.width=12, fig.height=8) 
library(tidyverse)
```


```{r}
df <- read.csv('C:\\Users\\maxim\\OneDrive - Montefiore Medicine\\Shechter\\Disorder_Analysis\\PTMscan_MethylArg_Residues_Withdisorder.csv')
df[grep('me1',df$value), 'group'] <- 'me1' 
df[grep('me2',df$value), 'group'] <- 'me2'
df2 <- df[c(12,13)]
df.m <- reshape2::melt(df2)

nrow(df2[df2$result == 'TRUE' & df2$group == 'me1',])/nrow(df2[df2$group == 'me1',])
nrow(df2[df2$result == 'TRUE' & df2$group == 'me2',])/nrow(df2[df2$group == 'me2',])


ggplot(data=df.m, aes(x=group, fill=result)) +
  geom_bar(stat="count", position='stack')+
  scale_fill_manual(values = c('#4d4d4d','#bababa'))+
    theme(legend.position = "right",
        axis.text.y   = element_text(size=12, colour = "black"),
        axis.text.x   = element_text(size=12, colour = "black", angle=90),
        axis.title.y  = element_text(size=12, colour = "black"),
        axis.title.x  = element_text(size=12, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #theme(axis.line = element_line(color = 'black', size = 1, linetype = 'solid'))+
  ylab('Fraction of Arginine Methylated Peptides')+
  xlab('IP')
```

